spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/altamim
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

app:
  jwt:
    token:
      expiration-in-ms: 86400000
    refresh:
      expiration-in-ms: 108000000